language: node_js

node_js:
  - "4.0"

env:
  global:
    secure: FvFZDR31xvciUNAyhjwl7ulO8KgRz/GSW7sH97gvrBxllFZFgbcqOeMIFi+jL0rmvHiC2dsBchK8kWckl94yEzjI2NIErvGTqw7M6KooZam7B5E7XtHO3OwZOeiIgOnNlzqu+rcB6a8W4BqZA4wRp9KKTMCpAZSzfFjPJU5Yu+opHL/iwvImQMR9ZdCeJeHppy/D0M3O+6TLMKMc2n+cAQqUR2KVi2dUrUp+IG7K0BC25NXWCeSOQ30vr9tk+mCDVNG/kT56mHBQoljosVWYARYeZm4svocqj1syHPsnqHbd/JPN9L5w+m61OxzoGO0CjWKwkICZvXghbuRZ80O9ehDOmMogilRZO+WyY649+olbcpaFAfSV7zXNeq217dv9O/pcTHficTLn/HYVWboyqFkAEc+PD1C4ud9GO0qzMYm0gxEV3xFVrCX0dT2gB6F7zHHwjDfoSqoUL6jvi8CX+FtuXqd/u12WZseGCqOwzL7jgGm+8UvyMiqy33WqlTVa30qXEESS+fKGXj3T573/SS3nzy8aZWAgL6w2bnt1tniMexDRPuQg1R/t+odjwqSV2iRi/mC50w1udXTiDPuyyoX53zMPIT82g+rpG0Rr7RQ38v4gNV3NMsMqGC4XQ4nTJuVCkWmEjPQH6xuyxqeVK6aDoneargWkbbq7DGVUIMU=

before_install:
  - export TZ=Asia/Taipei

install:
  - npm install

script:
  # Set Git config
  - git config --global user.name "$GIT_NAME"
  - git config --global user.email "$GIT_EMAIL"
  - git config --global push.default simple
  - git clone --depth 1 --branch gh-pages https://$GH_TOKEN@github.com/ssk7833/blog public
  # Generate Hexo static pages
  - npm run generate
  - cd public
  - git add -A .
  - MESSAGE=`date +\ %Y-%m-%d\ %H:%M:%S`
  - git commit -m "Site updated:$MESSAGE"
  - git push --quiet
